from pl_bolts.datamodules.bolts_dataloaders_base import BoltDataLoaders
from pl_bolts.datamodules.mnist_dataloaders import MNISTDataLoaders
from pl_bolts.datamodules.cifar10_dataloaders import CIFAR10DataLoaders
from pl_bolts.datamodules.stl10_dataloaders import STL10DataLoaders
